# Generated by Django 2.0.3 on 2018-03-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('num_bikes_available', models.PositiveSmallIntegerField()),
                ('num_docks_available', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
