# Generated by Django 2.0.3 on 2018-03-21 06:02

import bikesharestationcatalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharestationcatalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=bikesharestationcatalog.models.hash_image)),
                ('date', models.DateField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikesharestationcatalog.Station')),
            ],
        ),
    ]
