# Generated by Django 2.0.3 on 2018-05-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharestationcatalog', '0003_stationaveragelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationimage',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
